version: 0.0
os: linux
files:
  -source:  /
  destination: /home/ec2-user/app/step2/zip/
  overwrite: yes
  hooks:
  BeforeInstall:
  AfterInstall:
  ApplicationStart:
    - location: ./Deploy.bat
  timeout: 300
  ValidateService:
    - location: ./AfterService.bat
  timeout: 300
